const _ = require('lodash');

const timelineSourceEnums = {
  system: 'system',
  external: 'external',
  user: 'user',
  monitoring: 'monitoring',
};

const timelineEnums = {
  TIMELINE_SUPPLIER_CREATED: 'TIMELINE_SUPPLIER_CREATED',
  TIMELINE_PENDING_SUPPLIER: 'TIMELINE_PENDING_SUPPLIER',
  TIMELINE_SUPPLIER_ACTIVATED: 'TIMELINE_SUPPLIER_ACTIVATED',
  TIMELINE_MONITORING_EVENT: 'TIMELINE_MONITORING_EVENT',
  TIMELINE_SUPPLIER_INACTIVATED: 'TIMELINE_SUPPLIER_INACTIVATED',
  TIMELINE_SUPPLIER_REJECTED: 'TIMELINE_SUPPLIER_REJECTED',
  TIMELINE_SUPPLIER_BLOCKED: 'TIMELINE_SUPPLIER_BLOCKED',
  TIMELINE_SUPPLIER_AUTO_DEACTIVATED: 'TIMELINE_SUPPLIER_AUTO_DEACTIVATED',
  TIMELINE_INCOMINGINVOICE_DISPUTE_INTERNAL_CORRECTION:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_INTERNAL_CORRECTION',
  TIMELINE_INCOMINGINVOICE_DISPUTE_EXTERNAL_CORRECTION:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_EXTERNAL_CORRECTION',
  TIMELINE_INCOMINGINVOICE_DISPUTE_EMAIL_REQUIRED:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_EMAIL_REQUIRED',
  TIMELINE_INCOMINGINVOICE_SUPPLIER_BANKACCOUNT_CHANGE:
    'TIMELINE_INCOMINGINVOICE_SUPPLIER_BANKACCOUNT_CHANGE',
  TIMELINE_INCOMINGINVOICE_DISPUTE_EMAIL_SENT:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_EMAIL_SENT',
  TIMELINE_INCOMINGINVOICE_DISPUTE_VIEWED:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_VIEWED',
  TIMELINE_INCOMINGINVOICE_DISPUTE_RESOLVED:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_RESOLVED',
  TIMELINE_INCOMINGINVOICE_DISPUTE_CANCELLED:
    'TIMELINE_INCOMINGINVOICE_DISPUTE_CANCELLED',
  TIMELINE_INCOMINGINVOICE_COMMENT: 'TIMELINE_INCOMINGINVOICE_COMMENT',
  TIMELINE_INCOMINGINVOICE_STATUS_CHANGED:
    'TIMELINE_INCOMINGINVOICE_STATUS_CHANGED',
  TIMELINE_INCOMINGINVOICE_ASSIGNED: 'TIMELINE_INCOMINGINVOICE_ASSIGNED',
  TIMELINE_INCOMINGINVOICE_WF_STATUS_CHANGED:
    'TIMELINE_INCOMINGINVOICE_WF_STATUS_CHANGED',
  TIMELINE_INCOMINGINVOICE_WF_COMMENT: 'TIMELINE_INCOMINGINVOICE_WF_COMMENT',
  TIMELINE_INCOMINGINVOICE_RE_ASSIGNED: 'TIMELINE_INCOMINGINVOICE_RE_ASSIGNED',
  TIMELINE_INCOMINGINVOICE_RE_ASSIGNED_ON_SIGN:
    'TIMELINE_INCOMINGINVOICE_RE_ASSIGNED_ON_SIGN',
  TIMELINE_INCOMINGINVOICE_UNASSIGNED: 'TIMELINE_INCOMINGINVOICE_UNASSIGNED',
};

const listTimelineEnums = () => _.values(timelineEnums);

const listTimelineSourceEnums = () => _.values(timelineSourceEnums);

module.exports = {
  enums: timelineEnums,
  source: timelineSourceEnums,
  listTimelineEnums,
  listTimelineSourceEnums,
};
